Attribute VB_Name = "NEWACCOUNTMODULE"
Type NEWCTO
NEWNAME As String
NEWGENDER As String
NEWQUALIFICATION10 As String
NEWQUALIFICATION12 As String
NEWQUALIFICATIONG As String
NEWQUALIFICATIONPG As String
NEWPAN As String
NEWAADHAR As Double
NEWMOBILE As Double
NEWDOBD As Integer
NEWDOBM As Integer
NEWDOBY As Integer
NEWACCTNUMBER As Double
NEWACCTPASSWORD As Double
NEWPHOTO As String
NEWSIGNATURE As String
End Type

Global NEWACC As NEWCTO


